"""
Modelos SpeedGov - estrutura enviar_lote_rps.xml.
Não reutiliza modelos ABRASF - estrutura própria com p:/p1:.
"""
from pynfse.src.integration.carnaubal.speedgov.models.base import (
    CpfCnpj,
    Endereco,
)
from pynfse.src.integration.carnaubal.speedgov.models.rps import (
    Rps,
    InfRps,
    IdentificacaoRps,
    IdentificacaoPrestador,
    IdentificacaoTomador,
    DadosTomador,
    DadosServico,
    Valores,
    DadosDPS,
    EnderecoObra,
    DadosObra,
    ComercioExterior,
    ExigibilidadeSuspensa,
    BeneficioMunicipal,
    ReembolsoRepasse,
    Destinatario,
    ControleIBSCBS,
    IBSCBS,
)
from pynfse.src.integration.carnaubal.speedgov.models.lote import (
    LoteRps,
    ListaRps,
    EnviarLoteRpsEnvio,
)
from pynfse.src.integration.carnaubal.speedgov.models.respostas import (
    CancelarNfseResposta,
    CompNfse,
    ConsultarLoteRpsResposta,
    ConsultarNfseResposta,
    ConsultarNfseRpsResposta,
    ConsultarSituacaoLoteRpsResposta,
    EnviarLoteRpsResposta,
    InfNfse,
    ListaMensagemRetorno,
    ListaNfse,
    MensagemRetorno,
    Nfse,
    RespostasSpeedGov,
)

__all__ = [
    "CpfCnpj",
    "Endereco",
    "Rps",
    "InfRps",
    "IdentificacaoRps",
    "IdentificacaoPrestador",
    "IdentificacaoTomador",
    "DadosTomador",
    "DadosServico",
    "Valores",
    "DadosDPS",
    "EnderecoObra",
    "DadosObra",
    "ComercioExterior",
    "ExigibilidadeSuspensa",
    "BeneficioMunicipal",
    "ReembolsoRepasse",
    "Destinatario",
    "ControleIBSCBS",
    "IBSCBS",
    "LoteRps",
    "ListaRps",
    "EnviarLoteRpsEnvio",
    "EnviarLoteRpsResposta",
    "ConsultarNfseResposta",
    "ConsultarNfseRpsResposta",
    "ConsultarLoteRpsResposta",
    "ConsultarSituacaoLoteRpsResposta",
    "CancelarNfseResposta",
    "CompNfse",
    "ListaNfse",
    "ListaMensagemRetorno",
    "MensagemRetorno",
    "Nfse",
    "InfNfse",
    "RespostasSpeedGov",
]
